apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: allien/frontend:0.0.1
    name: frontend
    resources: {}
    env:
      - name: PORT
        value: "8080"
      - name: PRODUCT_CATALOG_SERVICE_ADDR
        value: "productcatalogservice:port"
      - name: CURRENCY_SERVICE_ADDR
        value: "currencyservice:port"
      - name: CART_SERVICE_ADDR
        value: "cartservice:port"
      - name: RECOMMENDATION_SERVICE_ADDR
        value: "recommendationservice:port"
      - name: SHIPPING_SERVICE_ADDR
        value: "shippingservice:port"
      - name: CHECKOUT_SERVICE_ADDR
        value: "checkoutservice:port"
      - name: AD_SERVICE_ADDR
        value: "adservice:port"
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
