apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: web
spec:
  containers:
    - name: web-app
      image: allien/web:0.1
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: app
          mountPath: /app
      readinessProbe:
        httpGet:
          path: /index.html
          port: 8000
      livenessProbe:
        tcpSocket:
          port: 8000
  initContainers:
    - name: init
      image: busybox:1.32.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts:
        - name: app
          mountPath: /app
  volumes:
    - name: app
      emptyDir: {}
